package:
  name: bayesass3-snp
  version: "v1.0.0"

source:
  git_url: https://github.com/smussmann82/BayesAss3-SNPs.git
  git_rev: v1.0.0

build:
  skip: True  # [win]

CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk        # [osx]

requirements:
  build:
    - clangxx_osx-64 # [osx]
    - gxx_linux-64 # [linux]
    - boost
    - gsl
  run:
    - boost
    - gsl

about:
  home: https://github.com/smussmann82/BayesAss3-SNPs
  license: GPLv3
  summary: Modification of BayesAss 3.0.4 to allow handling of large SNP datasets
